### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pablo-quilez** [nloyolag/connect4-ai#4]
Hello Noé,

we find your connect4-ai quite handy. We want to use it inside our software framework (https://dragandbot.com) as part of a robotic demonstrator for our customers. Unfortunately, there is no license file, which means Copyright applies. Would be ok for you to release the software under MIT, BSD or Apache 2 License? We are an small start-up and this would be very helpful for us.

Thanks in advance!
Pablo

**Comment by nloyolag** [comment]
Sorry to check this so late Pablo. You can use it. I will add a license. Not sure if it helps at this point XD
